### ISSUE TITLE
T11 - Realizar deploy da aplicação fora do Expo

### ISSUE THREAD

**Issue by AllanNobre** [fga-gpp-mds/2017.2-MerendaMais#120]
**Sugestões:**
- [x] Utilizar ferramenta do Expo para facilitar deploy;
- [x] Gerar APK Android;
- [ ] Fazer deploy na Play Store;

**Comment by Rdlenke** [comment]
Eu usei essa documentação <a href="https://docs.expo.io/versions/latest/guides/building-standalone-apps.html">aqui</a> pra poder gerar o APK com a ajuda do expo.

Basicamente, o que é necessário fazer é instalar o exp ```npm install -g exp```, e executar o comando ```exp build:android```.

Com esse comando, o expo provavelmente vai pedir um login e senha, que são o da minha conta, que é onde o aplicativo está agora. Se for necessário, eu passo a conta pra vocês colocarem como variável do sistema.

Depois disso, o expo vai começar a buildar o aplicativo. Vai demorar uns dois ou três minutos, mas depois de um tempo vai aparecer um link no terminal pra você baixar o apk. Se não aparecer, utilize o comando ```exp build:status```. Demora mesmo, mas confia que dá.

Limitações:
- Eu não sei se, mesmo com o expo, precisamos de Mac pra buildar pra iOs. Infelizmente não pude testar porque a App Store exige conta de desenvolvedor pra fazer esse esquema.
