### ISSUE TITLE
TS24 - Aplicar alterações requisitadas

### ISSUE THREAD

**Issue by AllanNobre** [fga-gpp-mds/2017.2-MerendaMais#129]
Eu, como desenvolvedor, desejo aplicar alterações requisitadas pelos stakeholders para que o software anteda as expectativas destes.

---

- [x] Mudanças relacionadas a **Pesquisar Escola**:
   - [x] (Sugestão) Os campos de pesquisar escola devem vir pré-preenchidos com os Dados da UF e do Município do conselheiro, no caso de não ser municipal deve vir em branco mesmo;
   - [x] (Sugestão) Mostrar número de Alunos nos dados da Escola Selecionada;
   - [x] (Problema) Verificar por que no DF não é possível pesquisar pelo termo “escola classe”, mas em outros Estados é possível;
   - [x] (Problema) O teclado, no IOS, está cobrindo o campo onde faz-se a pesquisa, assim não é possível ver o que é digitado -> @igor-gme ;

---

- [x] Mudanças relacionadas a **Tela de Checklists**:
   - [x] (Sugestão) O nome “**relatório**” deve ser trocado por “**lista de verificação**” e o botão “gerar relatório final” deve ficar como está, seguindo a seguinte lógica: o conselheiro preenche a **lista de verificação** para gerar o **relatório final** @LucasPenido @AllanNobre ;
   - [X] (Sugestão)  "Vocês tem essas listas digitadas em word da mesma forma que estão no app? Se sim, me mandem por favor que eu providencio essa padronização aqui." Deve-se mandar a lista em word ou link do drive para que a Cliente padronize os checklists da forma que achar melhor e não será necessária a mudança nas cores, somente nas sentenças das listas;
   - [x] (Sugestão) Atualizar as frases dos checklists da aplicação de acordo com o documento do Word ( Encontrado no Drive do Projeto) com as modificações feitas pela Cliente @LucasPenido @AllanNobre ;

---

- [X] Mudanças relacionadas a **Convidar Agente da Vigilância**:
   - [X] (Sugestão) Deve ser enviado um e-mail com um template pré definido e editável pelo conselheiro.
   - [X] (Sugestão) A Cliente irá verificar com o pessoal do CAE qual o e-mail destinatário, se será um e-mail geral da vigilância ou um e-mail de um agente específico.
   - [x] (Sugestão) Mudar de DropDown para campo de texto para a inserção do e-mail do Agente da Vigilância a ser convidado @hugo-asb .
   - [x] (Sugestão) Aplicar template de e-mail já enviado pela cliente (Encontrado no Drive do Projeto) com os dados preenchidos automaticamente exceto _telefone do CAE_ @hugo-asb @LucasPenido .

---

- [x] Mudanças relacionadas a **Editar Perfil do Conselheiro**:
   - [X] (Sugestão) Deve ser possível editar todos os dados do conselheiro, porém só os que a aplicação permiti fazer com segurança.
   - [x] (Sugestão) Tirar o botão Editar Dados da SideBar e colocar um botão ao final da tela de Perfil escrito "Editar Dados de Cadastro", que leva para a tela de editar Dados, quando os dados forem editados com sucesso, o conselheiro deve ser redirecionado para a tela de Perfil com o Toast informando que os dados foram modificados com sucesso (Usar Promise para esperar os dados serem modificados com sucesso na Nuvem e Usar lógica para renderizar novamente a tela de Perfil a fim de atualizar os dados e não somente dar um ".pop" ) @Rdlenke .

---

- [x] Mudanças relacionadas a **Convidar conselheiros**:
   - [x] Mudar as opções do Pop-Up de convite (Em todos os lugares que tem que convidar) de "aceitar" e "cancelar" para "convidar" e "cancelar" @LucasPenido @AllanNobre .

**Comment by LucasPenido** [comment]
Na task de verificar o porque não ser possível pesquisar escolas com o nome "Escola Classe". Foi verificado que no DF, e em alguns outros estados, as escolas com nome "Escola Classe", na verdade, estão salvas com a sigla EC.
