### ISSUE TITLE
Atualizem Suas contas github

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2017.2-MerendaMais#144]
Muitas pessoas desse time com conta Github ruim!

- [x] Coloquem a descrição de vocês em inglês

- [x] Coloquem o email/contato de vocês

- [x] Deixem em destaque os projetos que vocês tem colaborado!

Facilitem o mundo vê-los, e entrar em contato com vocês!

**Comment by AllanNobre** [comment]
Atualizado, se ainda estiver ruim me avisa ;-;.
