### ISSUE TITLE
US22 - Convidar Agente

### ISSUE THREAD

**Issue by Rdlenke** [fga-gpp-mds/2017.2-MerendaMais#24]
Eu, como conselheiro, desejo convidar um agente da vigilância sanitária para auxiliar na realização da fiscalização em uma escola.

- [x] Estudar como enviar emails utilizando o React Native. Pode ser dentro do aplicativo, ou um aplicativo de e-mail do celular do conselheiro.
- [ ] Abrir e-mail com um texto padrão para que o agente seja convidado.
  - Algo como "Solicito a presença do agente X para a realização da fiscalização no dia D, hora H, na Escola X, localizada no endereço 123. Link do maps, assinatura do conselheiro, etc".
  - É importante verificar se os CAEs pedem um agente aleatório, se mandam e-mail pro órgão como um todo, quais informações ele precisa informar - (PO deve mandar e-mail para a Marcela perguntando sobre como ou o que deve ter nesse e-mail além do padrão, e pra quem deve ser enviado, se terá algum e-mail padrão de agente ou se será aleatório, ou se terá um dropDown de emails para mandar).
- [x] Permitir que o usuário só convide um agente após selecionar a escola.
- [x] Enviar o e-mail quando o agendamento for concluído (Caso seja muito complexo, informar durante a Sprint para que soluções sejam encontradas).
- [ ] Quando os dados, o corpo do e-mail e o e-mail para o qual deve ser enviado for definido e confirmado, devem aparecer na tela de Agendamento com a mesma estrutura usada para mostrar os dados da escola.
- [ ] Testar

**Comment by hugo-asb** [comment]
Foi realizado o merge da história, porém os dados do email dos agentes e o texto padrão ainda não foram definidos pela cliente e por isso ela só está com esses dados default. No momento que a cliente der a resposta esses dados serão colocados na aplicação.
