### ISSUE TITLE
TS02 - Refatorar Tela de Login

### ISSUE THREAD

**Issue by Rdlenke** [fga-gpp-mds/2017.2-MerendaMais#32]
Eu, como desenvolvedor, desejo refatorar a Tela de Login, para aplicar a folha de estilo ao código.

**_Tasks_**:
- [x] Instalar a dependência no package.json (npm install);

- [x] Instalar o Plug-in no Atom: Linter-Eslint;

- [x] Código sem erros com a folha de estilo;

- [x] Criar o container referente a própria Tela;

**Comment by AllanNobre** [comment]
Esta TS é originária da Sprint 0 e se tornou uma dívida técnica por não ter sido concluída. Ela foi replanejada para a Sprint 1 e foi concluída nela.
