### ISSUE TITLE
TS20 - Organizar as rotas

### ISSUE THREAD

**Issue by Rdlenke** [fga-gpp-mds/2017.2-MerendaMais#43]
Eu, como desenvolvedor, desejo organizar as rotas do aplicativo para que o fluxo fique correto.

- [x] Sobrescrever o método de hardware **Back** do Android, de maneira que nas telas que são as primeiras folhas (as primeiras telas a partir da Main), o botão chame a função Actions.popTo('mainScreen');
- [x] Sobrescrever a chamada de função do botão de **Back** que fica no canto superior esquerdo das telas, para que, nas telas que são as primeiras folhas a partir da Main, o botão chame a função Actions.popTo('mainScreen');
- [x] Estudar e Aplicar solução a respeito do Actions.pop, para que, onde for necessário, a volta para a página na pilha seja feita de modo que ela seja renderizada novamente (Sugestões, verificar types nas routes, ou Actions.refresh que possa solucionar o problema - https://github.com/aksonov/react-native-router-flux/blob/master/README2.md);
- [x] Verificar se existem fluxos no aplicação de resultem em loops não tratados por essas implementações anteriores;

**Comment by AllanNobre** [comment]
Esta TS é originária da Sprint 5 e se tornou uma dívida técnica por não ter sido concluída. Ela foi replanejada para a Sprint 6 para ser concluída nela.
