### ISSUE TITLE
TS08 - Transferir usuário para Nuvem Cívica

### ISSUE THREAD

**Issue by Rdlenke** [fga-gpp-mds/2017.2-MerendaMais#50]
Eu, como desenvolvedor, desejo transferir o cadastro do usuário para Nuvem Cívica para que o Tribunal de Contas de União tenha um controle dos conselheiros cadastrados.

**_Tasks_**:

- [x] Estudar como o usuário é tratado na Nuvem Cívica;
- [x] Cadastrar usuários na Nuvem Cívica pelo login do aplicativo;
- [x] Verificar se há a necessidade de passar o usuário pela API;
- [x] Verificar como ficam os atributos extras na Nuvem Cívica (CAE, CAE_Type, Presidente/Conselheiro, etc), observando a estrutura de perfil;
- [x] Modificar a estrutura do React para utilizar a Nuvem ao invés da API (Registro, Login, Editar Dados);

**Comment by AllanNobre** [comment]
Esta TS é originária da Sprint 2 e se tornou uma dívida técnica por não ter sido concluída. Ela foi replanejada para a Sprint 3 e foi concluída nela.
