### ISSUE TITLE
Feedback - Sugestões

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2017.2-MerendaMais#80]
Muito transparente o trabalho de vcs! fácil acompanhar a execução da metodologia (planejamento, monitoramento e controle, prática ágeis). 

- [x] Retrospectiva em equipe me parece ser mais rico que retrospectiva individual (como a pontuação das histórias, a retrospectiva tem como objetivo gerar uma visão comum da sprint com a equipe)

- [x] A publicação das releases por sprint está ótimo! Fica a sugestão de registrar também em cada sprint os bugs encontrados, e as dividas técnicas pendentes

- [x] Qualidade/cobertura de testes - vcs estão fazendo? onde estão as evidências?

- [x] Evitar retrabalho (não é agil) - ao invés de criar as issues com história de usuário e depois copiar o mesmo texto na Wiki, na última faça somente referencia (link) à issue

- [x] Falta a project description e algumas outras boas práticas em projetos de software livre. Sugestão: deem uma olhada no "insights" do projeto de vcs. Lá tem muita informação boa. Checklist do projeto de vcs para atender as boas práticas da comunidade de software livre:
https://github.com/fga-gpp-mds/2017.2-MerendaMais/community

- [x] Foquem no nivelamento da equipe - se não estão mais desenvolvendo em Django, tirem do quadro de conhecimento. Trabalhem a auto estima de vcs (quero ver carinha azul na R2)!
http://www.claudiamelo.org/2016/11/25/principios-gestao-agil/

- [x] Compartilhem conquistas/riscos com os stakeholders. Sugestão: crie uma pagina sobre a núvem civida, e registrem as lições aprendidas sobre a plataforma. Abram issues no repositório da nuvem civica (comunicação via issues).

- [x] Se possivel, façam um esforço coletivo para fazer a retrospectiva e planning presencial. Importante a convivência da equipe!

**Comment by AllanNobre** [comment]
@RochaCarla Obrigado pelo feedback!
Uma dúvida, as lições aprendidas sobre a nuvem devem ser armazenadas como um documento na nossa própria Wiki mesmo ou existe alguma sugestão melhor? Já abrimos issues lá e estamos abrindo novas, isso deve ser registrado?

**Comment by RochaCarla** [comment]
@AllanNobre Registrem essas issues na wiki (como colaboraram com a nuvem). E criem uma página para registrar as lições aprendidas em relação à nuvem (também pode estar como uma seção no post mortem)
